# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Idd_data',
            fields=[
                ('idd', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('storage', models.CharField(max_length=255)),
                ('api', models.CharField(max_length=255)),
                ('dccode', models.CharField(max_length=255)),
                ('custcode', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'idd_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_name', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'shape',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SSHkeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_name', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sshkeys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tier',
                'managed': True,
            },
        ),
    ]
