# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170823_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authDomain', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('dccode', models.CharField(max_length=255)),
                ('custcode', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('shape', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('datavolsize', models.CharField(max_length=255, null=True)),
                ('appinstance', models.CharField(max_length=255, null=True)),
                ('backupvolsize', models.CharField(max_length=255, null=True)),
                ('hostlabel', models.CharField(max_length=255, null=True)),
                ('seclist', models.CharField(max_length=255, null=True)),
                ('tier', models.CharField(max_length=255, null=True)),
                ('instance', models.CharField(max_length=255, null=True)),
                ('ssh', models.CharField(max_length=255, null=True)),
                ('pagevolsize', models.CharField(max_length=255, null=True)),
                ('emvolsize', models.CharField(max_length=255, null=True)),
                ('datacenter', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': True,
            },
        ),
    ]
